import os

TOKEN = os.getenv("TOKEN")

CHANNEL_ID = "@AKNMedia"

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")

STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
PRICE_1_MONTH = "price_1Tr1njQ4IuPkYuATjSUy4CEz"

PRICE_3_MONTHS = "price_1Tr1u9Q4IuPkYuATujbQGPwX"

PRICE_12_MONTHS = "price_1Tr21JQ4IuPkYuATCbM9T1Z6"
